const mongoose=require("mongoose")
const validator=require("validator")
const orderSchema=new mongoose.Schema({
        owner:{
            type:mongoose.Schema.Types.ObjectId,
            required:true,
            trim:true
        },
        products:[{
            _id:{
                type:mongoose.Schema.Types.ObjectId,
                required:true,
                trim:true
            },
            name:{
                type:String,
                required:true,
                trim:true
            },
            itemTotal:{
                type:Number,
                required:true,
                trim:true
            },
            quantity:{
                type:Number,
                required:true,
                trim:true
            },status:{
                type:String,
                required:true,
                trim:true
            }
        }],
        orderTotal:{
            type:String,
            required:true,
            trim:true
        },
        deliveryAddress:{
                location:{
                    type:String,
                    required:true,
                    trim:true,
                    lowercase:true
                },
                pincode:{
                    type:Number,
                    required:true,
                    trim:true
                },
                city:{
                    type:String,
                    required:true,
                    trim:true,
                    lowercase:true,
                },
                state:{
                    type:String,
                    required:true,
                    trim:true,
                    lowercase:true,
                },
                name:{
                    type:String,
                    required:true,
                    trim:true,
                    lowercase:true,
                },
                phone:{
                    type:Number,
                    required:true,
                    trim:true,
                }
            },
        paymentMode:{
            type:String,
            required:true,
            trim:true
        }
    
},{
    timestamps:true
})

const Order=mongoose.model("Order",orderSchema)

module.exports=Order